server:
  port: 8762 #8762 8763

spring:
  application:
    name: serviceorder

eureka:
  client:
    #eureka client刷新本地缓存时间
    #默认30s
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/