eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
server:
  port: 8765
spring:
  application:
    name: client